import 'package:flutter/material.dart';

// الترجمة والتعريب للتطبيق
class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _translations = {
    'ar': {
      // عام
      'app_name': 'SIMO Player',
      'ok': 'موافق',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'search': 'بحث',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'retry': 'إعادة المحاولة',
      'success': 'تم بنجاح',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'confirm_delete': 'تأكيد الحذف',
      'yes': 'نعم',
      'no': 'لا',

      // الشاشة الرئيسية
      'home': 'الرئيسية',
      'channels': 'القنوات',
      'continue_watching': 'متابعة المشاهدة',
      'favorites': 'المفضلة',
      'categories': 'التصنيفات',
      'live': 'بث مباشر',
      'movies': 'أفلام',
      'series': 'مسلسلات',
      'no_channels': 'لا توجد قنوات. أضف مصدراً جديداً.',
      'add_source': 'إضافة مصدر',
      'all_channels': 'جميع القنوات',

      // المشغل
      'player': 'المشغل',
      'play': 'تشغيل',
      'pause': 'إيقاف مؤقت',
      'stop': 'إيقاف',
      'fullscreen': 'ملء الشاشة',
      'pip': 'صورة داخل صورة',
      'record': 'تسجيل',
      'stop_record': 'إيقاف التسجيل',
      'recording': 'جاري التسجيل',
      'source_switch': 'تغيير المصدر',
      'time_shift': 'إيقاف مؤقت للبث المباشر',
      'back_10': 'رجوع 10 ثوانٍ',
      'forward_10': 'تقديم 10 ثوانٍ',
      'stream_error': 'خطأ في تحميل البث',
      'trying_next_source': 'جاري تجربة المصدر التالي...',
      'no_sources_available': 'لا توجد مصادر متاحة',
      'buffering': 'جاري التحميل...',
      'quality': 'الجودة',
      'speed': 'السرعة',
      'audio_track': 'المسار الصوتي',
      'subtitles': 'الترجمة',
      'watch_party': 'غرفة مشاهدة',

      // قائمة القنوات
      'search_channels': 'بحث في القنوات...',
      'filter': 'تصفية',
      'sort': 'ترتيب',
      'grid_view': 'عرض شبكي',
      'list_view': 'عرض قائمة',
      'poster_view': 'عرض بوسترات',
      'add_to_favorites': 'إضافة للمفضلة',
      'remove_from_favorites': 'إزالة من المفضلة',
      'channel_info': 'معلومات القناة',
      'epg': 'دليل البرامج',
      'unavailable': 'غير متاحة',
      'available': 'متاحة',
      'checking': 'جاري الفحص...',

      // إضافة مصدر
      'source_type': 'نوع المصدر',
      'm3u_url': 'رابط M3U',
      'xtream_codes': 'Xtream Codes',
      'm3u_file': 'ملف M3U',
      'source_name': 'اسم المصدر',
      'server_url': 'رابط الخادم',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'loading_playlist': 'جاري تحميل قائمة التشغيل...',
      'playlist_loaded': 'تم تحميل القائمة بنجاح',
      'playlist_error': 'خطأ في تحميل القائمة',
      'channels_found': 'قناة تم العثور عليها',

      // دليل البرامج
      'now_playing': 'يُعرض الآن',
      'next': 'التالي',
      'program_guide': 'دليل البرامج',
      'no_epg': 'لا توجد بيانات برامج',
      'epg_url': 'رابط دليل البرامج',
      'load_epg': 'تحميل الدليل',
      'schedule_recording': 'جدولة تسجيل',

      // البحث
      'search_hint': 'ابحث عن قناة أو برنامج...',
      'voice_search': 'البحث الصوتي',
      'listening': 'جاري الاستماع...',
      'no_results': 'لا توجد نتائج',
      'recent_searches': 'عمليات البحث الأخيرة',
      'clear_history': 'مسح السجل',

      // الإعدادات
      'appearance': 'المظهر',
      'theme': 'الثيم',
      'theme_dark': 'داكن',
      'theme_light': 'فاتح',
      'theme_oled': 'OLED أسود',
      'theme_custom': 'ملون مخصص',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'الإنجليزية',
      'player_settings': 'إعدادات المشغل',
      'hardware_acceleration': 'تسريع الجهاز',
      'buffer_size': 'حجم المخزن المؤقت',
      'mb': 'ميغابايت',
      'sources': 'المصادر',
      'manage_sources': 'إدارة المصادر',
      'check_channels': 'فحص القنوات',
      'checking_channels': 'جاري فحص القنوات...',
      'account': 'الحساب',
      'sync_data': 'مزامنة البيانات',
      'remote_setup': 'الإعداد عن بُعد',
      'about': 'عن التطبيق',
      'version': 'الإصدار',
      'privacy_policy': 'سياسة الخصوصية',
      'connection_protection': 'حماية الاتصال',
      'vpn_not_installed': 'لا يوجد تطبيق VPN مثبت',
      'vpn_recommendation': 'يُنصح باستخدام VPN لحماية خصوصيتك',
      'advanced_settings': 'الإعدادات المتقدمة',
      'enable_rebranding': 'تمكين إعادة التسمية',

      // التسجيل
      'recordings': 'التسجيلات',
      'no_recordings': 'لا توجد تسجيلات',
      'scheduled': 'مجدولة',
      'completed': 'مكتملة',
      'recording_size': 'الحجم',
      'recording_duration': 'المدة',
      'play_recording': 'تشغيل التسجيل',
      'delete_recording': 'حذف التسجيل',
      'local_recordings': 'تسجيلات محلية',
      'cloud_recordings': 'تسجيلات سحابية',

      // غرفة المشاهدة
      'watch_party_title': 'غرفة مشاهدة جماعية',
      'create_room': 'إنشاء غرفة',
      'join_room': 'الانضمام لغرفة',
      'room_code': 'رمز الغرفة',
      'participants': 'المشاركون',
      'leave_room': 'مغادرة الغرفة',
      'copy_code': 'نسخ الرمز',
      'share_room': 'مشاركة الغرفة',
      'syncing': 'جاري المزامنة...',
      'synced': 'تمت المزامنة',

      // تسجيل الدخول
      'sign_in': 'تسجيل الدخول',
      'sign_in_google': 'تسجيل الدخول بـ Google',
      'sign_in_apple': 'تسجيل الدخول بـ Apple',
      'sign_in_huawei': 'تسجيل الدخول بـ Huawei',
      'skip_sign_in': 'تخطي (بدون حساب)',
      'sign_in_benefits': 'سجّل دخولك لمزامنة المفضلة والإعدادات عبر أجهزتك',

      // الملفات الشخصية
      'profiles': 'الملفات الشخصية',
      'select_profile': 'اختر ملفك الشخصي',
      'add_profile': 'إضافة ملف شخصي',
      'edit_profile': 'تعديل الملف الشخصي',
      'delete_profile': 'حذف الملف الشخصي',
      'profile_name': 'اسم الملف الشخصي',
      'profile_avatar': 'الصورة الرمزية',
      'manage_profiles': 'إدارة الملفات الشخصية',

      // الإعداد عن بعد
      'remote_setup_title': 'الإعداد عن بُعد',
      'scan_qr': 'امسح رمز QR بهاتفك',
      'qr_expires': 'ينتهي الرمز بعد',
      'qr_expired': 'انتهت صلاحية الرمز',
      'refresh_qr': 'تحديث الرمز',
      'transfer_success': 'تم نقل الإعدادات بنجاح',
      'transfer_failed': 'فشل نقل الإعدادات',
      'minutes': 'دقائق',
      'seconds': 'ثوانٍ',
    },
    'en': {
      'app_name': 'SIMO Player',
      'ok': 'OK',
      'cancel': 'Cancel',
      'close': 'Close',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'loading': 'Loading...',
      'error': 'Error',
      'retry': 'Retry',
      'success': 'Success',
      'settings': 'Settings',
      'logout': 'Logout',
      'confirm_delete': 'Confirm Delete',
      'yes': 'Yes',
      'no': 'No',
      'home': 'Home',
      'channels': 'Channels',
      'continue_watching': 'Continue Watching',
      'favorites': 'Favorites',
      'categories': 'Categories',
      'live': 'Live TV',
      'movies': 'Movies',
      'series': 'Series',
      'no_channels': 'No channels found. Add a source.',
      'add_source': 'Add Source',
      'all_channels': 'All Channels',
      'player': 'Player',
      'play': 'Play',
      'pause': 'Pause',
      'stop': 'Stop',
      'fullscreen': 'Fullscreen',
      'pip': 'Picture in Picture',
      'record': 'Record',
      'stop_record': 'Stop Recording',
      'recording': 'Recording...',
      'source_switch': 'Switch Source',
      'time_shift': 'Pause Live TV',
      'back_10': 'Back 10s',
      'forward_10': 'Forward 10s',
      'stream_error': 'Stream Error',
      'trying_next_source': 'Trying next source...',
      'no_sources_available': 'No sources available',
      'buffering': 'Buffering...',
      'quality': 'Quality',
      'speed': 'Speed',
      'audio_track': 'Audio Track',
      'subtitles': 'Subtitles',
      'watch_party': 'Watch Party',
      'search_channels': 'Search channels...',
      'filter': 'Filter',
      'sort': 'Sort',
      'grid_view': 'Grid View',
      'list_view': 'List View',
      'poster_view': 'Poster View',
      'add_to_favorites': 'Add to Favorites',
      'remove_from_favorites': 'Remove from Favorites',
      'channel_info': 'Channel Info',
      'epg': 'Program Guide',
      'unavailable': 'Unavailable',
      'available': 'Available',
      'checking': 'Checking...',
      'source_type': 'Source Type',
      'm3u_url': 'M3U URL',
      'xtream_codes': 'Xtream Codes',
      'm3u_file': 'M3U File',
      'source_name': 'Source Name',
      'server_url': 'Server URL',
      'username': 'Username',
      'password': 'Password',
      'loading_playlist': 'Loading playlist...',
      'playlist_loaded': 'Playlist loaded successfully',
      'playlist_error': 'Error loading playlist',
      'channels_found': 'channels found',
      'now_playing': 'Now Playing',
      'next': 'Next',
      'program_guide': 'Program Guide',
      'no_epg': 'No program data available',
      'epg_url': 'EPG URL',
      'load_epg': 'Load Guide',
      'schedule_recording': 'Schedule Recording',
      'search_hint': 'Search channels or programs...',
      'voice_search': 'Voice Search',
      'listening': 'Listening...',
      'no_results': 'No results found',
      'recent_searches': 'Recent Searches',
      'clear_history': 'Clear History',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'theme_dark': 'Dark',
      'theme_light': 'Light',
      'theme_oled': 'OLED Black',
      'theme_custom': 'Custom Color',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'player_settings': 'Player Settings',
      'hardware_acceleration': 'Hardware Acceleration',
      'buffer_size': 'Buffer Size',
      'mb': 'MB',
      'sources': 'Sources',
      'manage_sources': 'Manage Sources',
      'check_channels': 'Check Channels',
      'checking_channels': 'Checking channels...',
      'account': 'Account',
      'sync_data': 'Sync Data',
      'remote_setup': 'Remote Setup',
      'about': 'About',
      'version': 'Version',
      'privacy_policy': 'Privacy Policy',
      'connection_protection': 'Connection Protection',
      'vpn_not_installed': 'No VPN app installed',
      'vpn_recommendation': 'We recommend using a VPN to protect your privacy',
      'advanced_settings': 'Advanced Settings',
      'enable_rebranding': 'Enable Rebranding',
      'recordings': 'Recordings',
      'no_recordings': 'No recordings',
      'scheduled': 'Scheduled',
      'completed': 'Completed',
      'recording_size': 'Size',
      'recording_duration': 'Duration',
      'play_recording': 'Play Recording',
      'delete_recording': 'Delete Recording',
      'local_recordings': 'Local Recordings',
      'cloud_recordings': 'Cloud Recordings',
      'watch_party_title': 'Watch Party',
      'create_room': 'Create Room',
      'join_room': 'Join Room',
      'room_code': 'Room Code',
      'participants': 'Participants',
      'leave_room': 'Leave Room',
      'copy_code': 'Copy Code',
      'share_room': 'Share Room',
      'syncing': 'Syncing...',
      'synced': 'Synced',
      'sign_in': 'Sign In',
      'sign_in_google': 'Sign in with Google',
      'sign_in_apple': 'Sign in with Apple',
      'sign_in_huawei': 'Sign in with Huawei',
      'skip_sign_in': 'Skip (No Account)',
      'sign_in_benefits': 'Sign in to sync favorites and settings across devices',
      'profiles': 'Profiles',
      'select_profile': 'Select Profile',
      'add_profile': 'Add Profile',
      'edit_profile': 'Edit Profile',
      'delete_profile': 'Delete Profile',
      'profile_name': 'Profile Name',
      'profile_avatar': 'Avatar',
      'manage_profiles': 'Manage Profiles',
      'remote_setup_title': 'Remote Setup',
      'scan_qr': 'Scan QR with your phone',
      'qr_expires': 'Code expires in',
      'qr_expired': 'Code expired',
      'refresh_qr': 'Refresh Code',
      'transfer_success': 'Settings transferred successfully',
      'transfer_failed': 'Failed to transfer settings',
      'minutes': 'minutes',
      'seconds': 'seconds',
    },
  };

  String translate(String key) {
    return _translations[locale.languageCode]?[key] ?? key;
  }

  String get(String key) => translate(key);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// اختصار للوصول السريع للترجمة
extension LocalizationExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String key) => AppLocalizations.of(this).translate(key);
}
